### ISSUE TITLE
Application won't start

### ISSUE THREAD

**Issue by YocYoc** [marcos10soares/valheim-imacheater#2]
Hello,
I tried 1.2.0 and 1.3.0 and nothing happens when I execute the file, only the bckp folder is created. And nothing is writtent in the event viewer. I tried to disable the windows defender folder sercurity access too.

**Comment by marcos10soares** [comment]
> Hello,
> I tried 1.2.0 and 1.3.0 and nothing happens when I execute the file, only the bckp folder is created. And nothing is writtent in the event viewer. I tried to disable the windows defender folder sercurity access too.

Hi, do you have google chrome installed?

**Comment by YocYoc** [comment]
No, I didn't, but now that it is installed, it works.
Thank you.

**Comment by marcos10soares** [comment]
You're welcome, have fun! 👍
